defaults:
  - copious_base
  - _convert_documents
  - _select_n

add_partitions:
  function:
    pattern: "\n"

convert_documents:
  document_type: pytorch_ie.documents.TextDocumentWithLabeledEntities
